language: ruby
script: "bundle exec rake"
sudo: false
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - 2.4.1
  - ruby-head
  - jruby-head
  - jruby-19mode
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 1.8.7
    - rvm: jruby-18mode
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: ree
